spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:file:./data/cafeteriadb;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL}
spring.datasource.username=${JDBC_DATABASE_USERNAME:sa}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}

# Dialecto de PostgreSQL (para producción)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Crear/actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 (solo desarrollo local)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=true